#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}
SYNO=${SYNO:-false}
FPYVENV="/app/pyvenv"
RTXT="/app/requirements.txt"

if [[ ! -z ${PYVENV} ]] && [[ ! -d ${FPYVENV} ]]; then
    
    python3 -m venv ${FPYVENV} && source ${FPYVENV}/bin/activate
    if [[ -f ${RTXT} ]]; then
      pip3 install -r ${RTXT}
    fi
    if [ ! -z ${USER_NAME+x} ]; then
      chown -R ${PUID}:${PGID} ${FPYVENV}
    fi
    echo "Python virtual environment setup done!"
fi

PJSON="/app/package.json"
NMODULES="/app/node_modules"
if [[ ! -d ${NMODULES} ]] && [[ -f ${PJSON} ]]; then
  if [ ! -z ${USER_NAME+x} ]; then
    if $SYNO ; then
      helper --proc=install --dir="/app" --target="/app"  && \
      chown -R ${PUID}:${PGID} /nodepath && \
      cp -r /nodepath/app/node_modules /app && \
      chown -R ${PUID}:${PGID} /app/node_modules
      echo "Install nodepath done!"
    else
      cd /app &&  bun install --no-save --no-lockfile && chown -R ${PUID}:${PGID} node_modules
    fi    
  else
    if $SYNO ; then
      helper --proc=install --dir="/app" --target="/app"
    else
      cd /app &&  bun install --no-save --no-lockfile
    fi    
  fi
  echo "Install node_modules done!"
fi

echo “init-project-config done!”